# <ins>Workshop 1</ins>:

# Data Managment, Visualization, and Practical Example

* **Data Management**: Learn essential techniques for collecting, storing, and processing data to ensure its accuracy and accessibility. Understand the importance of data integrity and standardized data formats.

* **Visualization**: Explore various methods and tools for effectively visualizing data to reveal trends, patterns, and outliers. Discuss the principles of good data visualization and how to choose the right type of chart for different types of data.

* **Practical Example**: Apply the concepts in a hands-on project that involves data handling and visualization to derive actionable insights. This will include a case study to demonstrate the real-world application of the tools and techniques discussed.


<img src="https://cdn.analyticsvidhya.com/wp-content/uploads/2023/11/image-12.png" width="500" height="315" alt="Description of the image">

**<ins>Material generated by:</ins>**
- Martina C치diz Leyton
- Daniel Moreno Cartagena<br>

*Date: 06-10-2024*

---
---

This workshop will begin with a brief introduction to useful libraries for data management and visualization. The objective is to provide knowledge about the existence of these tools that you could use in future projects.


<ins>**Libraries for Data Management**</ins>

* **Pandas**: Ideal for structured data operations and manipulations. It is well-suited for different kinds of data, such as: tabular data with heterogeneously-typed columns, ordered and unordered time series data, arbitrary matrix data with row and column labels, and any other form of observational or statistical data sets.

* **Polars**: A fast multi-threaded DataFrame library that is optimized for performance and efficient memory use. Perfect for larger-than-memory datasets.

* **Spark**: Excellent for big data processing. Allows for data processing in batches or in real time, making it highly suitable for handling large-scale data across a cluster.

<ins>**Libraries for Visualization**</ins>

* **Matplotlib**: A robust library for creating static, animated, and interactive visualizations in Python. Perfect for those who need fine control over their plots.

* **Plotly**: Provides interactive plots and is accessible via a web browser; ideal for creating dashboards with dynamic visualizations.

* **Bokeh**: Great for creating interactive plots, dashboards, and data applications on modern web-browsers. It empowers the user to generate elegant and concise graphics akin to those of D3.js.

# Data Managment

## Pandas

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

### 1. Importing pandas

First, you need to import the pandas library. It's conventionally imported with the alias `pd`.

In [3]:
import pandas as pd

### 2. Creating DataFrames

DataFrames are the primary data structure in pandas. They are like tables in a database or Excel sheets.

**From a dictionary:**

In [4]:
data = {
    'ID': range(1, 11),
    'Name': ['John', 'Anna', 'Peter', 'Linda', 'James', 'Laura', 'Steve', 'Maria', 'Tom', 'Sue'],
    'Age': [28, 24, 35, 32, 45, 29, 41, 38, 23, 31],
    'City': ['New York', 'Paris', 'Berlin', 'London', 'Tokyo', 'Sydney', 'Moscow', 'Dubai', 'Toronto', 'Mumbai'],
    'Score': [85, 90, 78, 92, 88, 76, 84, 91, 87, 77],
    'Salary': [50000, 60000, 70000, None, 90000, 55000, None, 75000, 62000, 71000]  # Include some NaN values
}

df = pd.DataFrame(data)
df

   ID   Name  Age      City  Score   Salary
0   1   John   28  New York     85  50000.0
1   2   Anna   24     Paris     90  60000.0
2   3  Peter   35    Berlin     78  70000.0
3   4  Linda   32    London     92      NaN
4   5  James   45     Tokyo     88  90000.0
5   6  Laura   29    Sydney     76  55000.0
6   7  Steve   41    Moscow     84      NaN
7   8  Maria   38     Dubai     91  75000.0
8   9    Tom   23   Toronto     87  62000.0
9  10    Sue   31    Mumbai     77  71000.0

**From a CSV file:**

In [5]:
df = pd.read_csv('./pandas_polars_pyspark/df_input.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: './pandas_polars_pyspark/df_input.csv'

### 3. Viewing and Inspecting Data

**Basic Information:**

In [ ]:
print('First 5 rows:')
display(df.head())
print('*' * 50)

print('Last 5 rows:')
display(df.tail())
print('*' * 50)

print('DataFrame info:')
df_info = df.info()
print(df_info)
print('*' * 50)

print('Statistical summary:')
display(df.describe())
print('*' * 50)

print('DataFrame shape:', df.shape)
print('*' * 50)

### 4. Selecting Data

**Selecting columns:**

In [ ]:
print('Name column:')
display(df['Name'])
print('*' * 50)

print('Name, Age, and Salary columns:')
display(df[['Name', 'Age', 'Salary']])
print('*' * 50)

**Selecting rows:**

In [ ]:
print('Row by label (loc):')
display(df.loc[0])
print('*' * 50)

print('Row by position (iloc):')
display(df.iloc[0])
print('*' * 50)

**Slicing:**

In [ ]:
print('Rows from position 1 to 5:')
display(df[1:6])
print('*' * 50)

### 5. Filtering Data

In [ ]:
print('Rows where Age > 30:')
display(df[df['Age'] > 30])
print('*' * 50)

print('Rows where City is London:')
display(df[df['City'] == 'London'])
print('*' * 50)

### 6. Modifying Data

**Adding a new column:**

In [ ]:
df['Bonus'] = df['Score'] * 10
print('DataFrame with new Bonus column:')
display(df)
print('*' * 50)

**Updating values:**

In [ ]:
df.loc[0, 'Age'] = 29  # Update specific value
df['Age'] = df['Age'] + 1  # Increment all ages by 1
print('DataFrame with updated Age:')
display(df)
print('*' * 50)

### 7. Handling Missing Data

**Checking for missing values:**

In [ ]:
print('Missing values:')
display(df.isna())
print('*' * 50)

print('Count of missing values in each column:')
display(df.isna().sum())
print('*' * 50)

**Dropping missing values:**

In [ ]:
df_dropped = df.dropna()  # Drop rows with any missing values
print('DataFrame after dropping rows with missing values:')
display(df_dropped)
print('*' * 50)

**Filling missing values:**

In [ ]:
df_filled = df.fillna(0)  # Fill missing values with 0
print('DataFrame after filling missing values with 0:')
display(df_filled)
print('*' * 50)

### 8. Grouping and Aggregating Data

In [ ]:
# Group by 'City' and calculate the mean age, score, and salary
grouped = df.groupby('City').mean()
print('Grouped DataFrame (mean age, score, and salary by City):')
display(grouped)
print('*' * 50)

### 9. Merging and Joining DataFrames

**Merging:**

In [ ]:
data1 = {
    'ID': range(1, 6),
    'Name': ['John', 'Anna', 'Peter', 'Linda', 'James'],
    'Department': ['HR', 'IT', 'Finance', 'Marketing', 'HR']
}

data2 = {
    'ID': range(1, 6),
    'City': ['New York', 'Paris', 'Berlin', 'London', 'Tokyo'],
    'Salary': [50000, 60000, 70000, 80000, 90000]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

merged_df = pd.merge(df1, df2, on='ID')
print('Merged DataFrame:')
display(merged_df)
print('*' * 50)

**Joining:**

In [ ]:
df1 = df1.set_index('ID')
df2 = df2.set_index('ID')

joined_df = df1.join(df2)
print('Joined DataFrame:')
display(joined_df)
print('*' * 50)

### 10. Saving Data

In [ ]:
df.to_csv('./pandas_polars_pyspark/df_output.csv', index=False)  # Save DataFrame to CSV file
print('Large DataFrame saved to pandas_polars_pyspark/df_output.csv')
print('*' * 50)

## Polars

In [ ]:
!pip install polars

In [ ]:
import polars as pl

# Read CSV file
df = pl.read_csv('./pandas_polars_pyspark/df_input.csv')
df

### 2. DataFrame Operations

**Head and Tail**

In [ ]:
# Display the first few rows
display(df.head(5))

# Display the last few rows
display(df.tail(5))

**Selection columns and filtering rows**

In [ ]:
# Select specific columns
selected_df = df.select(['ID', 'Name', 'Age'])
print("\nSelected Columns:")
display(selected_df)

# Filter rows based on a condition
filtered_df = df.filter(pl.col('Age') > 30)
print("\nFiltered Rows (Age > 30):")
display(filtered_df)

**Aggregation**

In [ ]:
# Group by 'City' and calculate mean 'Score' and sum 'Salary'
agg_df = df.group_by('City').agg([
    pl.col('Score').mean().alias('mean_score'),
    pl.col('Salary').sum().alias('total_salary')
])
print("\nAggregated Data:")
display(agg_df)

### 3. Dealing with Missing Values

In [ ]:
# Fill missing values in 'Salary' with the mean salary
mean_salary = df['Salary'].mean()
filled_df = df.with_columns(pl.col('Salary').fill_null(mean_salary))
print("\nDataFrame with Missing Values Filled:")
display(filled_df)

## PySpark

In [ ]:
!pip install pyspark

### 1. Setting up Spark

In [ ]:
from pyspark.sql import SparkSession

# Create a Spark session
spark = SparkSession.builder \
    .appName("Data Processing with PySpark") \
    .getOrCreate()

### 2. Reading the Data

In [ ]:
# Read CSV file
df = spark.read.csv('./pandas_polars_pyspark/df_input.csv', header=True, inferSchema=True)
print("CSV DataFrame:")
df.show()

### 3. Selecting Columns

In [ ]:
# Select specific columns
selected_df = df.select('ID', 'Name', 'Age')
print("\nSelected Columns:")
selected_df.show()

### 4. Filtering Rows

In [ ]:
# Filter rows based on a condition
filtered_df = df.filter(df['Age'] > 30)
print("\nFiltered Rows (Age > 30):")
filtered_df.show()

### 5. Aggregating Data

In [ ]:
# Group by 'City' and calculate mean 'Score' and sum 'Salary'
from pyspark.sql.functions import mean, sum

agg_df = df.groupBy('City').agg(
    mean('Score').alias('mean_score'),
    sum('Salary').alias('total_salary')
)
print("\nAggregated Data:")
agg_df.show()

### 6. Dealing with Missing Values

In [ ]:
from pyspark.sql.functions import avg

# Fill missing values in 'Salary' with the mean salary
mean_salary = df.select(avg('Salary')).first()[0]
filled_df = df.na.fill({'Salary': mean_salary})
print("\nDataFrame with Missing Values Filled:")
filled_df.show()

### Summary

This tutorial covered the basics of creating, viewing, selecting, filtering, modifying, handling missing data, grouping, merging, and saving data in pandas. This should give you a solid foundation to start working with data using pandas. If you have specific questions or need further details on any topic, feel free to ask!

https://dzone.com/articles/comparing-pandas-polars-and-pyspark

https://medium.com/@benpinner1997/data-processing-pandas-vs-pyspark-vs-polars-fc1cdcb28725

# Visualization

## Matplotlib

### 1. Importing Matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# Sample data
x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

### 2. Basic Plotting

**Line Plot**

In [ ]:
# Creating the plot
plt.plot(x, y)

# Adding title and labels
plt.title("Simple Line Plot")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")

# Displaying the plot
plt.show()

**Scatter Plot**

In [ ]:
# Creating the scatter plot
plt.scatter(x, y)

# Adding title and labels
plt.title("Simple Scatter Plot")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")

# Displaying the plot
plt.show()

**Bar Charts**

In [ ]:
# Sample data
categories = ['A', 'B', 'C', 'D', 'E']
values = [5, 7, 3, 8, 6]

# Creating the bar chart
plt.bar(categories, values)

# Adding title and labels
plt.title("Simple Bar Chart")
plt.xlabel("Categories")
plt.ylabel("Values")

# Displaying the chart
plt.show()

In [ ]:
# Sample data
data = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5]

# Creating the histogram
plt.hist(data, bins=5, edgecolor='black')

# Adding title and labels
plt.title("Simple Histogram")
plt.xlabel("Value")
plt.ylabel("Frequency")

# Displaying the histogram
plt.show()

In [ ]:
# Sample data
labels = ['A', 'B', 'C', 'D']
sizes = [15, 30, 45, 10]

# Creating the pie chart
plt.pie(sizes, labels=labels, autopct='%1.1f%%')

# Adding title
plt.title("Simple Pie Chart")

# Displaying the chart
plt.show()

### 3. Customizing Plots

In [ ]:
# Sample data
x = [1, 2, 3, 4, 5]
y1 = [1, 4, 9, 16, 25]
y2 = [2, 3, 5, 7, 11]

**Adding Legends, setting limits, and grid**

In [ ]:
# Creating the plot
plt.plot(x, y1, label='y1: x^2')
plt.plot(x, y2, label='y2: prime numbers')

# Adding legend
plt.legend()

# Setting limits
plt.xlim(0, 6)
plt.ylim(0, 30)

# Adding title and labels
plt.title("Plot with Legend")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")

plt.grid()

# Displaying the plot
plt.show()

**Enlarging the size of the graphics, letters, ticks, and leaving some space between the text.**

In [ ]:
# Font size and padding variables
fs = 20  # Font size
pad = 13  # Padding

plt.figure(figsize=(9, 6))

# Creating the plot
plt.plot(x, y1, label='y1: x^2')
plt.plot(x, y2, label='y2: prime numbers')

# Adding legend
plt.legend(fontsize=fs-2)

# Setting limits
plt.xlim(0, 6)
plt.ylim(0, 30)

# Adding title and labels
plt.title("Plot with Legend", size=fs, pad=pad)
plt.xlabel("X-axis", fontsize=fs-2, labelpad=pad)
plt.ylabel("Y-axis", fontsize=fs-2, labelpad=pad)

plt.xticks(fontsize=fs-2)
plt.yticks(fontsize=fs-2)

plt.grid()

# Displaying the plot
plt.show()

### 4. Subplots

In [ ]:
# Sample data
x = [1, 2, 3, 4, 5]
y1 = [1, 4, 9, 16, 25]
y2 = [2, 3, 5, 7, 11]

# Font size and padding variables
fs = 20  # Font size
pad = 13  # Padding

# Creating subplots
plt.figure(figsize=(12, 6))

# First subplot
plt.subplot(1, 2, 1)  # (rows, columns, panel number)
plt.plot(x, y1, marker='o', linestyle='-', color='b', label='y1: x^2')
plt.title("First Plot", fontsize=fs, pad=pad)
plt.xlabel("X-axis", fontsize=fs-2, labelpad=pad)
plt.ylabel("Y-axis", fontsize=fs-2, labelpad=pad)
plt.legend(fontsize=fs-2)
plt.tick_params(axis='both', labelsize=fs-2)  # Set tick size

# Second subplot
plt.subplot(1, 2, 2)
plt.plot(x, y2, marker='s', linestyle='--', color='r', label='y2: prime numbers')
plt.title("Second Plot", fontsize=fs, pad=pad)
plt.xlabel("X-axis", fontsize=fs-2, labelpad=pad)
plt.ylabel("Y-axis", fontsize=fs-2, labelpad=pad)
plt.legend(fontsize=fs-2)
plt.grid(True)  # Adding grid
plt.tick_params(axis='both', labelsize=fs-2)  # Set tick size


# Adjust spacing between subplots
plt.tight_layout()  # Adjusted pad here for overall subplot spacing

# Displaying the plots
plt.show()

## Pyplot

In [ ]:
import plotly.express as px
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()
df = px.data.iris()  # Using Plotly's built-in Iris dataset

# Create a scatter plot
fig = px.scatter(df, x='sepal_length', y='sepal_width',
                 color='species',
                 labels={'species': 'Species', 'sepal_length': 'Sepal Length (cm)', 'sepal_width': 'Sepal Width (cm)'},
                 title='Iris Dataset: Sepal Length vs Sepal Width')

# Show the plot
fig.show()

## Bokeh

In [ ]:
!pip install bokeh

In [ ]:
from bokeh.plotting import figure, show, output_notebook
from bokeh.models import ColumnDataSource, HoverTool, CDSView, BooleanFilter
from sklearn.datasets import load_iris
import pandas as pd

# Load the Iris dataset
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

# Prepare the data source for Bokeh
source = ColumnDataSource(df)

# Create a new plot with a title and axis labels
p = figure(title="Iris Dataset: Sepal Length vs Sepal Width", x_axis_label='Sepal Length (cm)', y_axis_label='Sepal Width (cm)')

# Add a hover tool to display info
hover = HoverTool()
hover.tooltips = [("Species", "@species"), ("Sepal Length", "@{sepal length (cm)}"), ("Sepal Width", "@{sepal width (cm)}")]
p.add_tools(hover)

# Add the scatter plot
color_map = {'setosa': 'red', 'versicolor': 'green', 'virginica': 'blue'}
for species, color in color_map.items():
    subset = source.data['species'] == species
    p.circle('sepal length (cm)', 'sepal width (cm)', size=8, source=source, color=color, legend_label=species, view=CDSView(source=source, filters=[BooleanFilter(subset)]))

# Legend positioning
p.legend.location = "top_left"

# Output the plot to the notebook
output_notebook()
show(p)

# Practical Example: An Action-Oriented Analysis of Bike Station Performance

In urban environments, shared bike services provide a flexible transportation option that complements public transit and reduces traffic congestion. However, managing such a service efficiently requires deep insights into usage patterns and station performance. This project aims to harness the power of big data analytics to enhance the operational efficiency and customer satisfaction of a shared bike system.

Using a comprehensive dataset spanning two years of operations in a major city, this analysis will focus on evaluating the performance of bike rental stations. The data includes timestamps of rentals and returns, station identifiers, event types (rental or return), bike IDs, and user types (subscriber or casual customer). This rich dataset will allow us to uncover critical usage patterns and station performance metrics.

<img src="https://media.istockphoto.com/id/1199831184/vector/public-city-bicycle-sharing-business-vector-flat-illustration-modern-automated-bike-rental.jpg?s=612x612&w=0&k=20&c=Ln20cn_A_xHqJ56iNBhbN8PEXl1ZBal5cwGpfbyWo2Q=" alt="Description of the image">

**Dataset characteristics:**

- datetime: hourly date + timestamp  
- season:  1 = spring, 2 = summer, 3 = fall, 4 = winter
- holiday: whether the day is considered a holiday
- workingday: whether the day is neither a weekend nor holiday
- weather:
  - 1: Clear, Few clouds, Partly cloudy, Partly cloudy
  - 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist
  - 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds
  - 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog
- temp: temperature in Celsius
- atemp: "feels like" temperature in Celsius
- humidity: relative humidity
- windspeed: wind speed
- casual: number of non-registered user rentals initiated
- registered: number of registered user rentals initiated
- count: number of total rentals

## Objectives

* **Analyze Peak Usage Times:** By understanding when bikes are most frequently rented and returned, we can optimize bike availability to meet demand.
* **Analyze Variation in Rental Demand:** Identify predictable trends in user demand, allowing for smarter resource allocation and operational planning.
* **Understand User Preferences:** Differentiate between subscriber and casual user behaviors to tailor services and promotions effectively.

## Exploratory Data Analysis (EDA):

Exploratory Data Analysis includes:

* **Descriptive Analysis:** Basic statistics (mean, median, mode, ranges) to understand the distributions of variables such as temperature, humidity, wind speed, and number of rentals.
* **Correlations:** Assess the correlation between the number of bikes rented and other variables such as temperature, humidity, and wind speed.
* **Visualizations:** Line and bar graphs for temporal trends, scatter plots for relationships between continuous variables, and heat maps for correlations.

To conduct thorough exploratory data analysis, consider answering the following questions:

1. How does bike rental vary across different months?
2. How does bike rental vary across different years, days, and hours of the day?
3. Is there a significant difference in bike usage between weekdays, weekends, and holidays?
4. How do temperature and humidity influence bike rentals?
5. What is the contribution of registered versus casual users in the total rentals?

In [ ]:
import pandas as pd

import matplotlib.pyplot as plt

In [ ]:
data_train = pd.read_csv('dataset_practical_example/train.csv')

### 1. How does bike rental vary across different months?

But what happens if we add more information to the problem and consider other variables for analyzing the average bike rentals by month, such as temperature, humidity, apparent temperature, and wind speed?

In [ ]:
month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

fs = 18

# Extract month from datetime
data_train['month'] = data_train['datetime'].dt.month

# Group data by month and calculate average rentals, temperature, and humidity
monthly_data = data_train.groupby('month').agg({
    'count': 'mean',        # Average rentals
    'temp': 'mean',         # Average temperature
    'humidity': 'mean'      # Average humidity
}).reset_index()

# Plotting the results in subplots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(18, 6), sharey=True)  # 1 row, 2 columns

# First subplot for Temperature and Bike Rentals
ax1.bar(monthly_data['month'], monthly_data['count'], color='skyblue', label='Bike Rentals')
ax1.set_xlabel('Month', fontsize=fs)
ax1.set_ylabel('Average Bike Rentals', fontsize=fs, color='b')
ax1.tick_params(axis='x', labelsize=fs-2)
ax1.tick_params(axis='y', labelcolor='b', labelsize=fs-2)
ax1.set_xticks(monthly_data['month'])
ax1.set_xticklabels(month_names)
ax1.set_title('Bike Rentals and Temperature', pad=13, size=fs+2)

# Second subplot for Humidity and Bike Rentals
ax2.bar(monthly_data['month'], monthly_data['count'], color='lightgreen', label='Bike Rentals')
ax2.set_xlabel('Month', fontsize=fs)
ax2.set_ylabel('Average Bike Rentals', fontsize=fs, color='b')
ax2.tick_params(axis='x', labelsize=fs-2)
ax2.tick_params(axis='y', labelcolor='b', labelsize=fs-2)
ax2.set_xticks(monthly_data['month'])
ax2.set_xticklabels(month_names)
ax2.set_title('Bike Rentals and Humidity', pad=13, size=fs+2)

# Create a second y-axis for temperature
ax3 = ax1.twinx()
ax3.plot(monthly_data['month'], monthly_data['temp'], color='r', marker='o', label='Temperature (춿C)')
ax3.set_ylabel('Temperature (춿C)', fontsize=fs, color='r')
ax3.tick_params(axis='y', labelcolor='r', labelsize=fs-2)

# Create a second y-axis for humidity
ax4 = ax2.twinx()
ax4.plot(monthly_data['month'], monthly_data['humidity'], color='g', marker='x', label='Humidity (%)')
ax4.set_ylabel('Humidity (%)', fontsize=fs, color='g')
ax4.tick_params(axis='y', labelcolor='g', labelsize=fs-2)

plt.tight_layout()
plt.show()

**(To do) What happens with atemp and windspeed?**

**We already analized what happend with the bike rental regarding the month, but**

### 2. How does bike rental vary across different years, days, and hours of the day?

**Years**

**Days**

**Hours**

### 3. Is there a significant difference in bike usage between weekdays, weekends, and holidays?

**(To do) Can you see any difference? What happens if you plot the values by hour of the day?**

The idea here is to show you that data can be analyzed in different ways to extract relevant information that can help us make decisions.

### 4. How do temperature and humidity influence bike rentals?

### 5. What is the contribution of registered versus casual users in the total rentals?